#!/bin/bash

######### commands specific to this project #############

# ${PBP}/t2t rmgeometry <$1.drawio | tee /tmp/stage1.txt|\
#     ${PBP}/t2t cull |\
#     ${PBP}/t2t rmdiv |\
#     ${PBP}/t2t rmspan |\
#     ${PBP}/t2t unhtml |\
#     ${PBP}/t2t rnet2swipl |\
#     ./commas.py

${PBP}/t2t rmgeometry <$1.drawio | tee /tmp/stage1.txt|\
    ${PBP}/t2t cull |\
    ${PBP}/t2t rmdiv |\
    ${PBP}/t2t rmspan |\
    ${PBP}/t2t unhtml |\
    ${PBP}/t2t kinds

############################



