#!/bin/bash

######### commands specific to this project #############

# ${PBP}/t2t rmgeometry <$1.drawio | tee /tmp/stage1.txt|\
#     ${PBP}/t2t cull |\
#     ${PBP}/t2t rmdiv |\
#     ${PBP}/t2t rmspan |\
#     ${PBP}/t2t unhtml |\
#     ${PBP}/t2t rnet2swipl |\
#     ./commas.py

./id_first.py <$1.drawio |\
    ${PBP}/t2t rmgeometry | tee /tmp/stage1.txt|\
    ${PBP}/t2t cull |\
    ${PBP}/t2t rmdiv |\
    ${PBP}/t2t rmspan |\
    ${PBP}/t2t unhtml |\
    ${PBP}/t2t kinds |\
    ${PBP}/del_blank_lines >out.mr
    ${PBP}/t2t rnet2swipl <out.mr | sort >out.pl

############################



